name: SetHome
version: 1.2
api-version: 1.16
author: Eltik
main: eltik.set.home.Core
commands:
  sethome:
    description: Sets home.
  home:
    description: Teleports you home.
  homes:
    description: Gives the homes GUI.
  delhome:
    description: Deletes the home.